@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Person(salesAgent,"Sales agent", "Person who works for an insurance agency")

Container(spa, "Agent Frontend Single-Page App", "Blazor WASM", "Agents login, browse products,create offers and sell policies, review their sales stats, chat with each other")

Container(apiGw, "API Gateway", ".net core, Ocelot", "Gives SPA apps access to microservices")

Container(productCatalog, "Product catalog", ".net core, minimal API, MongoClient", "Provides access to list of insurance products and their details")
Container(policyService, "Policy Service", ".net core, minimal API, NHibernate", "Manages offers, and policies")
Container(pricingService, "Pricing Service", ".net core, minimal API, Marten", "Calculates prices")

ContainerDb(productCatalogDb, "Product catalog db", "Mongodb" , "Products data")
ContainerDb(policyServiceDb, "Policies db", "Postgresql 16" , "Offers and policies")
ContainerDb(pricingServiceDb, "Tariffs db", "Postgresql 16" , "Tariffs")


Rel(salesAgent,spa,"searches for product, creates offers, sells policies, reviews sales stats, chats with other")
    Rel(spa,apiGw, "Makes API calls", "REST JSON/HTTP")
    Rel(apiGw, productCatalog, "Get products", "REST JSON/HTTP")
    Rel(productCatalog, productCatalogDb, "Reads/writes data", "MongoClient")

    Rel(apiGw, policyService, "Create offers and policies", "REST JSON/HTTP")
    Rel(policyService, policyServiceDb, "Reads/writes data", "NHibernate")

    Rel(policyService, pricingService, "calc price", "REST JSON/HTTP")
    Rel(pricingService, pricingServiceDb, "Reads/writes data", "Marten")
@enduml